objects/Case_Contact__c/Case_Contact__c.object-meta.xml
<CustomObject>
    <label>Case Contact</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Case Contact Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case_Contact__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <description>Contact that is attached to the Case</description>
    <inlineHelpText>Contact that is attached to the Case</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Case Contacts</relationshipLabel>
    <relationshipName>Case_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Case_Contact__c/fields/Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Contact_Role__c</fullName>
    <description>What Role is this Contact within this Case</description>
    <inlineHelpText>What Role is this Contact within this Case</inlineHelpText>
    <label>Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent</fullName>
            </value>
            <value>
                <fullName>Doctor</fullName>
            </value>
            <value>
                <fullName>Victim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/Case_Contact__c/fields/Law_Case__c.field-meta.xml
<CustomField>
    <fullName>Law_Case__c</fullName>
    <description>Law Case for this Contact and Role</description>
    <inlineHelpText>Law Case for this Contact and Role</inlineHelpText>
    <label>Law Case</label>
    <referenceTo>Law_Case__c</referenceTo>
    <relationshipLabel>Case Contacts</relationshipLabel>
    <relationshipName>Case_Contacts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/Law_Case__c/Law_Case__c.object-meta.xml
<CustomObject>
    <description>Legal Cases preformed and under consideration</description>
    <label>Law Case</label>
    <nameField>
        <label>Law Case Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Law Cases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/dcm_LawCaseContact_Controller.cls
public with sharing class dcm_LawCaseContact_Controller {
    @AuraEnabled
    public static List<Case_Contact__c> getLawCaseContacts(String strLawCaseId){
        List<Case_Contact__c> contacts = [SELECT Id, Name, Contact__c, Contact__r.Name, Contact__r.Account.Name, Contact_Role__c FROM Case_Contact__c WHERE Law_Case__c = :strLawCaseId];
        return contacts;
    }

    @AuraEnabled
    public static void deleteCaseContactRecord(String strCaseContactId){
        delete [SELECT Id FROM Case_Contact__c WHERE Id = :strCaseContactId];
    }

}